// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:miru/modules/bangumi/bangumi_item.dart';
import 'package:miru/modules/bangumi/bangumi_tag.dart';
import 'package:miru/modules/collect/collect_change_module.dart';
import 'package:miru/modules/collect/collect_module.dart';
import 'package:miru/modules/download/download_module.dart';
import 'package:miru/modules/history/history_module.dart';
import 'package:miru/modules/search/search_history_module.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BangumiItemAdapter());
    registerAdapter(BangumiTagAdapter());
    registerAdapter(CollectedBangumiAdapter());
    registerAdapter(CollectedBangumiChangeAdapter());
    registerAdapter(DownloadEpisodeAdapter());
    registerAdapter(DownloadRecordAdapter());
    registerAdapter(HistoryAdapter());
    registerAdapter(ProgressAdapter());
    registerAdapter(SearchHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BangumiItemAdapter());
    registerAdapter(BangumiTagAdapter());
    registerAdapter(CollectedBangumiAdapter());
    registerAdapter(CollectedBangumiChangeAdapter());
    registerAdapter(DownloadEpisodeAdapter());
    registerAdapter(DownloadRecordAdapter());
    registerAdapter(HistoryAdapter());
    registerAdapter(ProgressAdapter());
    registerAdapter(SearchHistoryAdapter());
  }
}
