name: "PR workflow"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - 'fastlane/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      run_android:
        description: 'manually run android build'
        required: false
        default: false
        type: boolean

env:
  DANDANAPI_APPID: ${{ secrets.DANDANAPI_APPID }}
  DANDANAPI_KEY: ${{ secrets.DANDANAPI_KEY }}
  KAZUMI_APPID: ${{ secrets.KAZUMI_APPID }}
  KAZUMI_KEY: ${{ secrets.KAZUMI_KEY }}

jobs:
  flutter-test:
    if: ${{ github.event_name == 'workflow_dispatch' || ! github.event.pull_request.draft }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
      - name: Run Flutter tests
        run: flutter test
        shell: bash

  flutter-analyze:
    if: ${{ github.event_name == 'workflow_dispatch' || ! github.event.pull_request.draft }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
      - name: Analyze Flutter project
        run: flutter analyze --no-fatal-infos --fatal-warnings
        shell: bash

  flutter-build-android:
    needs: [flutter-test, flutter-analyze]
    if: ${{ github.event_name == 'pull_request' && ! github.event.pull_request.draft || github.event_name == 'workflow_dispatch' }}
    name: "Release for android"
    runs-on: "ubuntu-latest"
    permissions: write-all
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libasound2-dev
        shell: bash
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        id: flutter-action
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get Flutter dependencies
        run: flutter pub get
        shell: bash
      - name: Remove build id
        run: sed -i -e 's/-Wl,/-Wl,--build-id=none,/' ${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}/hosted/pub.dev/jni-*/src/CMakeLists.txt
      - name: Print Flutter version
        run: flutter doctor -v
        shell: bash
      - name: Build Flutter for Android
        run: >-
          flutter build apk --split-per-abi
          --dart-define=DANDANAPI_APPID=$DANDANAPI_APPID
          --dart-define=DANDANAPI_KEY=$DANDANAPI_KEY
          --dart-define=KAZUMI_APPID=$KAZUMI_APPID
          --dart-define=KAZUMI_KEY=$KAZUMI_KEY
        shell: bash
      - name: Package android build output
        run: cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk Miru_android_canary.apk
        shell: bash
      - name: Upload android outputs
        uses: actions/upload-artifact@v4
        with:
          name: android_outputs
          path: Miru_android_*.apk